### ISSUE TITLE
Import from 1password archives (1pif)

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup#128]
Support importing from 1password archives (Requires 1pif export type).

This is blocked by buttercup-pw/buttercup-importer#4.

**Comment by zeke** [comment]
As a current 1password user considering trying Buttercup, this feature was the first thing I thought of.

**Comment by perry-mitchell** [comment]
This is now dependent on buttercup/buttercup-importer#9 being merged and released.

**Comment by perry-mitchell** [comment]
Buttercup importer v0.8.0 has support for 1password.

**Comment by zeke** [comment]
🎉
