### ISSUE TITLE
It's not possible to select a nameless group

### ISSUE THREAD

**Issue by lietu** [buttercup/buttercup#190]
I ended up with a nameless group during import from KeePass 1.x to 2.x, and I didn't notice that. Buttercup then happily imported the nameless group from the KeePass 2.x -file, but the UI makes it impossible to select it.

![image](https://cloud.githubusercontent.com/assets/1296558/24421195/0d05e7f6-13fe-11e7-8f64-161b360c2a9f.png)

Moving everything else out of the parent group and deleting it was a reasonable workaround for me, but it is not the best possible option. I think right-clicking on the folder icon should also be made to work.

**Comment by sallar** [comment]
The way we handle unnamed groups (both in importing and creating new groups) need to be improved. Thanks.
