### ISSUE TITLE
Register file associations on Windows

### ISSUE THREAD

**Issue by lietu** [buttercup/buttercup#191]
Registering file associations makes a few things a bit more convenient on Windows, and I believe is required for a "Recent" -list for the application to work. Pinning seems to work as it is though, so it's not super important, just a nice convenience feature to have.

https://msdn.microsoft.com/en-us/library/windows/desktop/cc144156(v=vs.85).aspx

![image](https://cloud.githubusercontent.com/assets/1296558/24421651/88be977a-13ff-11e7-8701-684dfb1394c2.png)

**Comment by sallar** [comment]
@lietu We already register the file associations in all platforms, and it **should** work in Windows too. Does it not work? Here's how it looks in macOS:

<img src='https://shipusercontent.com/c493ec65ab05a65a4e82d088277ccc84/Pasted%20Image%201.png' title='Pasted Image 1.png' width=290>

**Comment by lietu** [comment]
It didn't work for me. Double-clicking on the "unknown file" says Buttercup is probably able to open it, but it should open it with Buttercup by default if they were properly registered.

![image](https://cloud.githubusercontent.com/assets/1296558/24423074/724020cc-1404-11e7-9550-bd501daf82c3.png)

**Comment by sallar** [comment]
Then this is a bug. Thanks.

**Comment by sallar** [comment]
@lietu Also this should have been resolved in `0.15.0`, can you try again?

**Comment by lietu** [comment]
Perfect, seems to work fine now.
