### ISSUE TITLE
More keyboard shortcuts, especially to copy username

### ISSUE THREAD

**Issue by lietu** [buttercup/buttercup#192]
As an old KeePass user I really miss the ability to use Ctrl+B to copy the username for the selected entry

![image](https://cloud.githubusercontent.com/assets/1296558/24421921/6457b37a-1400-11e7-8a81-829651aa6e8b.png)

Similarly I'm used to Ctrl+F to find, and Ctrl+Y to create new entries, but these I use much less frequently as Ctrl+B to copy & paste a username and then Ctrl+C to copy & paste a password.

From the use of Ctrl over Cmd I'm sure you can guess that I'm on Windows, and these shortcuts should likely be platform dependent.

**Comment by sallar** [comment]
Thanks @lietu,
Buttercup already supports that, but it's Ctrl/Cmd + C, perhaps we need to make it more clear. If you press Ctrl + C now and an entry is selected, it's password will be written to clipboard. But I agree we need to support more shortcuts

**Comment by lietu** [comment]
Yes, there is already a "Copy password" shortcut, but not copy username, or am I mistaken?

**Comment by sallar** [comment]
No you're right. Maybe a better "Keyboard Shortcut Manager" can solve this problem.
