### ISSUE TITLE
Installing yarn dependencies fails on Windows

### ISSUE THREAD

**Issue by lietu** [buttercup/buttercup#193]
It seems there's a hard dependency to `macos-alias`, which is not surprisingly incompatible with the win32 platform.

![image](https://cloud.githubusercontent.com/assets/1296558/24422557/9c63faba-1402-11e7-86b4-99bbc53205ec.png)

However, `npm install` seems to work, mentioning these:

```npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.0.3 (node_modules\7zip-bin\node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.0.3: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules\7zip-bin\node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@^0.3.2 (node_modules\electron-installer-dmg\node_modules\appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.3.10: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})```

**Comment by perry-mitchell** [comment]
@sallar Any idea with regards to yarn handling these optional dependencies? Seems that `macos-alias` is the culprit but it doesn't even show up in @lietu's npm logs (I would expect it to read like the others).

Maybe we add a note for windows users to stick with npm temporarily?

**Comment by dealloc** [comment]
I can confirm that the same error occurs on Linux as well (Arch linux 4.10 with NPM 4.4.4 and NodeJS 7.7.3)

**Comment by perry-mitchell** [comment]
@dealloc What version of yarn did you try with?

@sallar Seems to be some larger issue with Yarn atm.. perhaps we can recommend npm as the primary installation medium? 

There's deeper issues here which we can't affect:

- yarnpkg/yarn#1059 Properly ignoring optionaDependencies
- yarnpkg/yarn#1233 Issues with the --ignore-optional flag

**Comment by sallar** [comment]
@perry-mitchell if it's really a Yarn thing and nothing that we have done in the `package.json` then we should definitely warn the users in README

**Comment by dealloc** [comment]
@perry-mitchell I'm using Yarn v0.21.3

**Comment by sallar** [comment]
@lietu @dealloc Can you please try again in master? I tried to reproduce with a fresh installation of Windows and Yarn, and I was able to install master correctly. Maybe the breaking module is gone?

**Comment by perry-mitchell** [comment]
Would also obviously be a good idea to try with the latest yarn.. :)

**Comment by dealloc** [comment]
I managed to install, build and run the latest version successfully this time

I'm using yarn 0.23.2

**Comment by lietu** [comment]
Well, it seems to be going better now, but it's still not exactly working. Some electron-chromedriver issues now, probably a temporary issue.

```
error C:\source\buttercup\node_modules\electron-chromedriver: Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c node ./download-chromedriver.js
Directory: C:\source\buttercup\node_modules\electron-chromedriver
Output:
C:\source\buttercup\node_modules\electron-chromedriver\download-chromedriver.js:16
  if (error != null) throw error
                     ^

Error: Generated checksum for "chromedriver-v2.21-win32-x64.zip" did not match expected checksum.
    at ChecksumMismatchError.Error (native)
    at ChecksumMismatchError.ErrorWithFilename (C:\source\buttercup\node_modules\sumchecker\build.js:41:124)
    at new ChecksumMismatchError (C:\source\buttercup\node_modules\sumchecker\build.js:56:133)
    at Hash.<anonymous> (C:\source\buttercup\node_modules\sumchecker\build.js:203:22)

    at emitNone (events.js:86:13)
    at Hash.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Hash.Readable.push (_stream_readable.js:134:10)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by dealloc** [comment]
@lietu I had the same error at first, simply retrying the installation fixed it for me though, no clue how that worked

**Comment by perry-mitchell** [comment]
If you could try it after clearing node modules and cache that would be awesome :)

**Comment by lietu** [comment]
Probably was an upstream issue, tried it now and it worked fine.
