### ISSUE TITLE
Support for Basic Auth login

### ISSUE THREAD

**Issue by codeclown** [buttercup/buttercup#198]
This is a feature request/enquiry. Regardless of the fact that Basic Auth is insecure, it is often used in developer environments to e.g. temporarily conceal a not-yet-published app/site.

Some password managers do support Basic Auth (e.g. [LastPass](https://lastpass.com/support.php?cmd=showfaq&id=275)), others do not (e.g. [1Password](https://discussions.agilebits.com/discussion/26753/basic-http-authentication-for-chrome-feature-request/p1)).

Is there or will there be support for Basic Auth login in the browser extension?

**Comment by perry-mitchell** [comment]
Hi @codeclown - thanks for making an issue.

Currently there is not, but there's no reason that we could choose not to support it. I'd just like to understand the use-case a bit better before fleshing it out fully.

So I understand basic auth, but I've never actually seen a site that uses it (or at least not to my knowledge). Do you know if any online that do, or demo projects that allow it? I could set it up myself but I'm afraid that I'd miss the point and not implement something entirely helpful.

It looks that basic auth is just continually sending a header like `Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l` for example, over and over for each request to that site.. right?

**Comment by perry-mitchell** [comment]
As this has to do with the browser extension, I've moved it there: buttercup-pw/buttercup-browser-extension#59
