### ISSUE TITLE
Clear clipboard after time

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup#2]
After a timeout, clear the clipboard when the user copies anything from an entry form.

**Comment by perry-mitchell** [comment]
Perhaps refer to the [clipboard notes on the electron repo](https://github.com/electron/electron/blob/master/docs/api/clipboard.md).

**Comment by sallar** [comment]
I think this depends on #140, since we don't want this to be enabled by default. user might have something in their clipboard that can be lost by this change.

**Comment by lietu** [comment]
Why wouldn't you want this enabled by default? You could likely stop unintentional clears by reading the clipboard contents first and confirming it's the same as what was last copied there.

This is imo a basic security feature in all password managers that should be enabled by default.

**Comment by perry-mitchell** [comment]
I think this definitely should be enabled by default. Leaving stuff like that in clipboard is very dangerous. I think we could set a default time period to start with and perhaps add the possibility to _adjust_ that later, imo.

**Comment by lietu** [comment]
I agree @perry-mitchell, the default on other apps seems to be 10s.

**Comment by sallar** [comment]
@lietu @perry-mitchell I agree that it should be on by default, but maybe we should check the content to see if it's the same as what we copied last. so we don't delete user's data by accident. Imagine after copying and using their password, they have copied some important information to paste in a note or something and exactly at that moment, our cleanup runs and deletes user's important info.

**Comment by perry-mitchell** [comment]
Ok.. so it looks like we have something to go on then. Not sure if I love the 10s default (15 maybe?), but otherwise it doesn't matter (we can change it later of course). All we need is this and the UI for it #134 and it should be golden.
