### ISSUE TITLE
Clearer font for passwords

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup#200]
The current font in the GUI is beautiful, but can sometimes look a bit ambiguous when viewing passwords:

![image](https://cloud.githubusercontent.com/assets/3869469/24577621/e98f60c0-16d9-11e7-9ed8-e7da1898f4b8.png)

(such as with 0 and O)

Perhaps a monospace font would be best - like one that distinguishes better between certain characters:

![image](https://cloud.githubusercontent.com/assets/3869469/24577630/0f6c4380-16da-11e7-9c26-7c5f678ec341.png)

**Comment by perry-mitchell** [comment]
What do you think @sallar ?

**Comment by sallar** [comment]
I agree @perry-mitchell, let's do that!

**Comment by fonzai** [comment]
1password has this nice subtle way to make numbers even more distinguishable by coloring them differently than alphabets. Maybe you could do something similar? <img width="273" alt="screenshot 2017-04-03 16 19 03" src="https://cloud.githubusercontent.com/assets/283121/24611032/73018bc0-1889-11e7-8f8c-e267c49b1c2c.png">

**Comment by sallar** [comment]
Great idea @fonzai 👍

**Comment by perry-mitchell** [comment]
What about a combination here? A font like [Anonymous Pro](https://fonts.google.com/specimen/Anonymous+Pro) or [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono) with digit highlighting? What do you think @sallar?

**Comment by sallar** [comment]
@perry-mitchell I have implemented the highlighting, but using the default monospace font which doesn't look so good. This Anonymous Pro that you've linked is looking pretty sweet, I'll post a screenshot here :+1:

**Comment by sallar** [comment]
@perry-mitchell @fonzai What do you guys think about this?
<img src='https://shipusercontent.com/a67e4f387d1b4fefa365bda067d7bb54/Pasted%20Image%201.png' title='Pasted Image 1.png' width=449>

**Comment by perry-mitchell** [comment]
Looks great! Could you show what the dupes look like beside each other? Like LlI|ij1oO0 for example.. :)

**Comment by sallar** [comment]
@perry-mitchell

<img src='https://shipusercontent.com/26e3b49689ebb80304f98c72e664dc40/Pasted%20Image%202.png' title='Pasted Image 2.png' width=289>

**Comment by perry-mitchell** [comment]
Beautiful!
