### ISSUE TITLE
"Click here to automatically download" and "Download for Desktop" links don't work

### ISSUE THREAD

**Issue by limonte** [buttercup/buttercup#203]
![](https://i.imgur.com/ZLvgSEz.png)

![](https://i.imgur.com/K1Hd8QP.png)

**Comment by sallar** [comment]
Thanks @limonte, there is currently a problem with our Update server that causes this.

**Comment by sallar** [comment]
@limonte Can you please check this out again to see if it works or not?

**Comment by limonte** [comment]
@sallar still no :)

**Comment by sallar** [comment]
@limonte I just changed some filenames for Windows. what about now? I tried https://download.buttercup.pw in Windows 10 and it worked.

**Comment by limonte** [comment]
still the same issue

**Comment by sallar** [comment]
@limonte interesting. what's the exact version (your OS)?

**Comment by limonte** [comment]
Linux Mint latest / Chrome latest

**Comment by sallar** [comment]
@limonte So which package would be the right package to download?

**Comment by limonte** [comment]
the latest? :)

**Comment by sallar** [comment]
I mean `deb`, `rpm`, `AppImage`? @limonte

**Comment by limonte** [comment]
deb

**Comment by sallar** [comment]
Is the system arch 64bit? `buttercup_0.15.0_amd64.deb`

**Comment by limonte** [comment]
yup

**Comment by sallar** [comment]
@limonte found the issue. and it should be fixed now. by the default the `.tar.gz` build will be triggered for linux. and if you need to download deb or rpm, you need to check releases page or click on related links on the homepage which I will put up tonight. Can you please confirm that the default download link is now fixed?

**Comment by sallar** [comment]
So the buttercup website will now show separate deb/rpm links when visited on linux. https://buttercup.pw/

**Comment by limonte** [comment]
https://buttercup.pw/ works now, but still this link in README doesn't 
![](https://i.imgur.com/OlcEwsa.png)

**Comment by sallar** [comment]
Thanks @limonte, updated that link too. Closing this.
