### ISSUE TITLE
Nextcloud archive access

### ISSUE THREAD

**Issue by jancborchardt** [buttercup/buttercup#205]
Similar to https://github.com/buttercup/buttercup/issues/39, it should be easy to add since Nextcloud is a community-driven fork of OwnCloud and we use WebDAV too. :)

See more info at https://github.com/nextcloud

**Comment by perry-mitchell** [comment]
Thanks @jancborchardt. This needs to be added in buttercup-core also: buttercup/buttercup-core#147

**Comment by sallar** [comment]
@jancborchardt @perry-mitchell if its a fork of owncloud, wouldnt it work same as owncloud? Because write now the code for owncloud and webdav are exactly the same except some url modifications. So what happens if we use "owncloud" adapter and just rename it in the UI? Will it work?

**Comment by perry-mitchell** [comment]
> Will it work?

It should definitely, yes. That being said it would be nice to officially support it. Extending the datasource would be trivial across core+desktop+browser, but we'd just need to test it properly.

**Comment by sallar** [comment]
Anyway its nice to add support for more sources especially when they're this easy to implement.

**Comment by sallar** [comment]
@jancborchardt @perry-mitchell I just tried Nextcloud :) It's exactly the same as OwnCloud, so I'll just alias the functionality in the GUI. 
<img src='https://shipusercontent.com/cecebbcccc704aa69d66ebe97030dfc6/Pasted%20Image%201.png' title='Pasted Image 1.png' width=982>

**Comment by perry-mitchell** [comment]
But let's not use the owncloud data source though :) That will create confusion with saved data source types..

**Comment by sallar** [comment]
@perry-mitchell there's two parts to it, the file manager which is using `any-fs` and `webdav-fs`, and the `datasource` in `buttercup-core`. Then I'll wait for the `buttercup-core`'s Nextcloud support before implementing the first part here. But I guess the datasource is an exact copy of OwnCloud isn't it? Only with a different name.

**Comment by perry-mitchell** [comment]
Well it’ll extend the nextcloud datasource.. so if next cloud uses /remote.php/webdav/ from the root then yes it’ll be mostly identical. Having the name means that it can be treated separately and retain its own name and identity in all of our interfaces.

**Comment by sallar** [comment]
@perry-mitchell yeah it is `/remote.php/webdav/`.

**Comment by perry-mitchell** [comment]
MR is blocked due to unexpected results from Nextcloud servers. Needs further assistance / investigation.
