### ISSUE TITLE
Unable to connect to Yandex Disk using WebDAV

### ISSUE THREAD

**Issue by C-A-T9LIFE** [buttercup/buttercup#206]
Do not connect https://webdav.yandex.ru and http://webdav.yandex.ru.

**Comment by perry-mitchell** [comment]
@C-A-T9LIFE Thanks for filing. Is there any way you could check using [webdav-client](https://github.com/perry-mitchell/webdav-client)? It's what we use in buttercup to connect WebDAV accounts.

**Comment by C-A-T9LIFE** [comment]
Make the compiled client under Windows?

**Comment by perry-mitchell** [comment]
> Make the compiled client under Windows?

I'm not sure what you mean. If you're talking about this project it can be built on windows using the readme instructions. If you mean the **webdav-client** project then yes, it should also work on windows: `npm install webdav-client`. If you use the example in _that_ readme with your credentials and the yandex path you're having trouble with, that would really help with debugging.

**Comment by C-A-T9LIFE** [comment]
hmmm
I meant need webdav-client-0.5.0.exe. That would test work on Windows 10

**Comment by perry-mitchell** [comment]
> Works, but it's bad.

What do you mean?

**Comment by perry-mitchell** [comment]
@sallar Seems that there may be something wrong with WebDAV. I also couldn't get it to work with Yandex in the interface, but it works with `webdav-client` on the command line:

![image](https://cloud.githubusercontent.com/assets/3869469/24993632/e41229de-202f-11e7-9d65-7916d7f2125c.png)

I'll test with webdav-fs soon. If that works then there may be a bug.

**Comment by sallar** [comment]
@perry-mitchell I'm using `any-fs` and `webdav-fs` to connect to WebDAV, but Im not doing any modification on the URL, passing it directly to `any-fs`. We should investigate more.

**Comment by perry-mitchell** [comment]
@sallar It works in any-fs currently, so the problem must lie elsewhere:

```js
const AnyFS = require("./index.js");
const wfs = require("webdav-fs")(
    "https://webdav.yandex.ru",
    "username",
    "password"
);
const afs = AnyFS(wfs);

afs
    .readDirectory("/")
    .then(function(contents) {
        console.log(contents);
    });
```

**Comment by sallar** [comment]
@perry-mitchell so after I use any-fs to connect, I pass the information to WebDAVDatasource in buttercup-core-web. But since we don't have good error handling for this (my bad) it's not obvious where is the error. I filed #207 too.

**Comment by perry-mitchell** [comment]
Ok, so let's check this out as an isolated issue then. We might be missing something somewhere. Obviously 2-factor won't work with yandex, but regular user/pass should.

I removed the milestone as we could fix this faster as a bug. Perhaps no need to add a specific datasource for yandex as they just promote their webdav connector.

**Comment by sallar** [comment]
@perry-mitchell sure, I still think it's a minor bug. I will look into the GUI part today, and if it's GUI, I can release a patch. But if it's core you might want to look into it. Thanks

**Comment by perry-mitchell** [comment]
@sallar Sure. I guess any broken connectivity on a working webdav service is a higher prio though, if people can't use it. Obviously if the bug lies elsewhere we can link from here - but the issue is still present in the GUI so it'll need to trickle into a patch release.

**Comment by perry-mitchell** [comment]
So there seems to be some combination of factors here.. At least the reload happens due to some other error, causing the webdav request to fail. No idea why it doesn't happen with other providers (yet), but there's some complication with yandex and the dialog.

**Comment by perry-mitchell** [comment]
@C-A-T9LIFE You could give version 0.12.1 a try with Yandex, the issue should now be fixed.

**Comment by wtsiamruk** [comment]
The issue is present on ios client, did not check for othe clients
