### ISSUE TITLE
Entering the exact path in dialog adds extra ".bcup"

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup#210]
When entering a new filename in a WebDAV connection, entering say "test.bcup" will produce "test.bcup.bcup":

![image](https://cloud.githubusercontent.com/assets/3869469/25065291/0dedc938-2216-11e7-95b8-71c8c46974a9.png)

Perhaps the suffix should be detected? For instance:

```javascript
const filename = /\.bcup$/i.test(enteredFilename) ?
    enteredFilename :
    `${enteredFilename}.bcup`;
```

**Comment by sallar** [comment]
@perry-mitchell darn, I forgot to add sanitizer to that field. Now it also accepts all kinds of wrong charatcers which are not valid as file name. That should also be fixed with this.

**Comment by perry-mitchell** [comment]
> all kinds of wrong charatcers which are not valid as file name

@sallar What do you mean? I guess it could of course contain other alphabetical chars from other languages.. but you mean slashes `/` and dots `.`?

**Comment by sallar** [comment]
the valid ones are these AFAIK: `/[\w\-. ]+/`

**Comment by perry-mitchell** [comment]
> `/[\w\-. ]+/`

What about underscore, square brackets etc? Maybe something like `/[\w._~$\[\]-]+/`?
