### ISSUE TITLE
Items in trash should have separate context menu

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup#217]
When right-clicking, items in the trash are not explicitly deletable:

![image](https://cloud.githubusercontent.com/assets/3869469/25071953/37cdcb2a-22cc-11e7-96cc-ec7c596fb9d1.png)

**Comment by perry-mitchell** [comment]
@sallar Is this new functionality that's needed or some kind of bug?

**Comment by sallar** [comment]
@perry-mitchell both... Now I only have access to parentCategoryId in the entry list but I should have more info to recognize im right clicking in Trash. but it's a bug

**Comment by perry-mitchell** [comment]
This could be detected by checking every entry's `isInTrash()` 😊

**Comment by sallar** [comment]
@perry-mitchell super! didn't know that's a thing haha
