### ISSUE TITLE
404 error on Windows trying to open an archive

### ISSUE THREAD

**Issue by smxsm** [buttercup/buttercup#222]
I have a weird issue (sorry, once again :P) since 0.12.0 on Windows (desktop app) - I select a WebDAV archive, enter the server data, I am connected and see the files on the server, then select the .bcup file, enter the (correct) master password and **THEN** I get a 404 error and cannot open the archive ... works fine on MAC with the same server and archive file! Here is a screen showing the error in the dev tools:
![buttercup_masterpw_404](https://cloud.githubusercontent.com/assets/1737182/25074092/62286d1c-22f4-11e7-96b2-6eac0babf844.png)

On a side note and probably unrelated to this issue, the Chrome extension seems to be gone in the Chrome web store and the  "Chrome Extension" link on the buttercup.pw website gives a 404 error, too: https://chrome.google.com/webstore/detail/buttercup/heflipieckodmcppbnembejjmabajjjj?hl=en

**Comment by sallar** [comment]
Thanks @smxsm, we will look into this.

**Comment by smxsm** [comment]
Just verified that on another WIN machine, seems to be a general WIN problem with opening WebDAV archives.

**Comment by perry-mitchell** [comment]
@smxsm Have you tried again on 0.12.2 at least? https://github.com/buttercup/buttercup/releases/tag/v0.12.2-alpha

It had some webdav tweaks.

**Comment by smxsm** [comment]
Sure, always trying new versions :) I'm running on 0.12.2. and problem is still there :(

**Comment by sallar** [comment]
@smxsm Found the issue. This will get fixed in next release soon :)

**Comment by smxsm** [comment]
Works now, thank you! 👍
