### ISSUE TITLE
Additional admin password / read-only mode?

### ISSUE THREAD

**Issue by smxsm** [buttercup/buttercup#230]
A **suggestion / question**: would it be hard to add an _"administrator" role_ for Buttercup? E.g. if you want to share an archive with colleagues / friends, but don't want them to change anything ... so that they'd have a "normal" password to open the archive in read-only mode and the admin/author has the master password which allows him to modify the archive?

**Comment by perry-mitchell** [comment]
@smxsm this is actually planned for a future product which is currently in development. Sharing via traditional sources (Dropbox/WebDAV) with read only mode is not really possible, as the user could still write to the cloud storage provider (even by accident), overwriting the original "read only" file.

The only way to do this is to have a service which manages "accounts", and permissions could be controlled in a more centralised manner. I won't reveal too much more, but this **is** in the works.

**Comment by perry-mitchell** [comment]
That being said, there will also be a host-your-own buttercup server option soonish. I think we would also be open to some kind of sharing there as well.

**Comment by perry-mitchell** [comment]
@smxsm for now I'll close this, as the work will be undertaken as in our [roadmap](https://github.com/buttercup/roadmap/blob/master/roadmap/BUTTERCUP_DESKTOP.md).

**Comment by smxsm** [comment]
Ah, interesting, so there will be a team version I guess, cool :) Sounds promising, thanks for the roadmap link, I was missing that one!
