### ISSUE TITLE
Connect to Dropbox account

### ISSUE THREAD

**Issue by scharepmc2hr** [buttercup/buttercup#231]
I can't connect to my Dropbox account!

![buttercup1](https://cloud.githubusercontent.com/assets/22997685/25428526/61f27a10-2a8b-11e7-96c0-426f8d00685a.PNG)

![buttercup2](https://cloud.githubusercontent.com/assets/22997685/25428548/6b402b30-2a8b-11e7-95a9-e4580f6d7e2b.PNG)

**Comment by perry-mitchell** [comment]
0 bytes? That looks interesting.. I wonder if it didn't initialise properly. What do you think @sallar? Also, we should figure out why the error is stringifying whatever data there is into `[object Object]`.

@scharepmc2hr we might need more to reproduce this.. Could you possibly try creating a local archive first, saving that, then upload that to dropbox and try to open it using the Dropbox option in buttercup? If we could narrow it down that'd help a lot.

**Comment by scharepmc2hr** [comment]
same problem...
but I download the latest version (v0.13.0-alpha), the issue has been fixed.

sorry for the delay in replying to your comment.
