### ISSUE TITLE
download.buttercup.pw distributes outdated version of the software

### ISSUE THREAD

**Issue by d2s** [buttercup/buttercup#248]
When trying to download latest release (as instructed in the main [README](https://raw.githubusercontent.com/buttercup/buttercup/master/README.md) file), server gives out badly outdated version of Buttercup.

```
## Download & Install
[Click here to automatically download](https://download.buttercup.pw) the latest release for your OS …
```

`Buttercup-0.14.1.dmg` is probably the same as `0.14.0` that was released on 12 Feb 2016.

Apparently the downloads sub-domain distributes over one year old version to new potential users. This might be an issue, as it gives a wrong impression on the state of Buttercup development, as over one year of additional development has been happening after that release.

**Comment by perry-mitchell** [comment]
Hi @d2s - Thanks for posting. Are you currently using windows to produce this issue?

**Comment by d2s** [comment]
macOS, so the platform version was right, but version number clearly way too old.

**Comment by sallar** [comment]
@d2s Can you try this please? :)

**Comment by d2s** [comment]
@sallar Did try the https://download.buttercup.pw page again (with latest Chrome 58 version).

Got the following file:
![screen shot 2017-05-15 at 20 49 09 buttercup download](https://cloud.githubusercontent.com/assets/135053/26071270/2b52e31c-39b0-11e7-8575-f722621ca36e.png)

![screen shot 2017-05-15 at 20 49 48 buttercup download](https://cloud.githubusercontent.com/assets/135053/26071272/2d8fc398-39b0-11e7-9e02-c4526dd2cad6.png)

**Comment by perry-mitchell** [comment]
@d2s @sallar So that looks correct to me - 0.14.3 is the latest version. Are there any further issues here?

**Comment by d2s** [comment]
My mistake === invalid bug report. 😞 

Apparently I had mixed up the repositories, and
had been looking at the release history of [`buttercup-core`](https://github.com/buttercup/buttercup-core/releases?after=v0.19.0) instead of [`buttercup`](https://github.com/buttercup/buttercup/releases).

![screen shot 2017-05-15 at 23 12 39 buttercup core release number](https://cloud.githubusercontent.com/assets/135053/26077323/561e2994-39c4-11e7-8af0-496bd7371bcc.png)
