### ISSUE TITLE
Catch unhandled production errors and present error message

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup#253]
Would we benefit from using something like this? https://github.com/sindresorhus/electron-unhandled

~At least more errors might be seen, if and when they appear. Thoughts @sallar?~

This would not be the prettiest solution, but it would help catch some issues in the wild that we have not foreseen. Users can contribute descriptions/screenshots with more information if these modals are present.

**Comment by sallar** [comment]
@perry-mitchell Agreed :+1:
