### ISSUE TITLE
Custom scrollbars missing

### ISSUE THREAD

**Issue by mikebowering** [buttercup/buttercup#258]
Hi @sallar,

The custom scrollbars introduced in v0.13.0 appear to have reverted back to the usual default window ones in the latest v0.15.0 release. OS is Windows 10. Wasn't sure if this was intentional - if so happily ignore 👍  
![image](https://cloud.githubusercontent.com/assets/1456740/26243758/e48ff636-3c84-11e7-9048-8bbe572cee3a.png)

Cheers!
Mike

**Comment by perry-mitchell** [comment]
Thanks @mikebowering - yes it seems as though they have reverted, also on linux:

![image](https://cloud.githubusercontent.com/assets/3869469/26244644/3d421fd4-3c99-11e7-871e-343ac4054493.png)

Thanks for letting us know. This definitely wasn't intentional.

**Comment by sallar** [comment]
Thanks @mikebowering and sorry for the trouble. @perry-mitchell this is interesting. I checked the scrollbar is definitely in the code base, maybe I should release again today.

**Comment by perry-mitchell** [comment]
Let's do a private build first - could you send me the deb file after building @sallar? :)

**Comment by sallar** [comment]
@mikebowering sorry for the problem, it is now fixed and released: https://github.com/buttercup/buttercup/releases/tag/v0.16.0 :+1:

**Comment by mikebowering** [comment]
@sallar that was lightning quick ⚡️ 😁 
awesome work 👍
