### ISSUE TITLE
Cant't create new wallet in Chrome extension 

### ISSUE THREAD

**Issue by andre-dierker** [buttercup/buttercup#260]
Hi,

my first try with Buttercup stops with creating a new wallet in Chrome extension in any Webdav location.
I tried Owncloud/Nextcloud what is in fact pure Webdav, I think, a naked nginx and my Synolog Nas.

When trying to get directory listing on my Nas over pure http, nothing happens.

When trying to get directory listing on my Nas over https, nothing happens, but a console output appears
`setup.views.js:33 PROPFIND https://192.168.2.20:5006/ net::ERR_INSECURE_RESPONSE`

Getting directory listing from Nextcloud which is driven by a nginx or a pure nginx is working fine. Creating new wallet ends in a 401 error code
`PUT /remote.php/webdav/Buttercup/wallet.bcup HTTP/1.1" 401 233 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"`

**Comment by sallar** [comment]
Hi, thanks for reporting this issue. I think Nextcloud has a problem with our Webdav module which we encountered while implementing Nextcloud support in #239. We have asked Nextcloud's maintainers for help but we haven't received any so far. Hopefully they will answer and we can resolve this issue.

**Comment by andre-dierker** [comment]
Hey, these Problems are not only related to Nextcloud. 
Neither my Nas  (Synology with WebDav enabled) nor the nginx webserver (with WebDav) are able to handle the Buttercup "put" request due to missing "Auth Header" when using https.

**Comment by perry-mitchell** [comment]
> due to missing "Auth Header" when using https

I don't see how this can be the case, as I can confirm I see it sent all the time for several ownCloud instances (mine is also running HTTPS). The only clean/stable way we found was to use the `Authorization` header, which works the same over HTTP/HTTPS.

This line looks like the response from the server was bad ('**response**'):

`setup.views.js:33 PROPFIND https://192.168.2.20:5006/ net::ERR_INSECURE_RESPONSE`

As for the nginx server, this could easily be misconfiguration or some incompatibility we haven't foreseen. It would be best if we could see the interaction between the services - otherwise we can't move forward with debugging.

@andre-dierker would it be possible for you to try the [chrome extension](https://chrome.google.com/webstore/detail/buttercup/heflipieckodmcppbnembejjmabajjjj?hl=en-GB)? You could open up devtools while running it and export a HAR file - you could share this with us, obviously after removing any sensitive hashes etc.. You could also email it to us at info@buttercup.pw so that it's not shared to the public. This transaction would definitely help us see where the problem is.

**Comment by andre-dierker** [comment]
this is from trying to create a wallet on my Nas
`{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [],
    "entries": [
      {
        "startedDateTime": "2017-05-20T18:00:29.613Z",
        "time": 0,
        "request": {
          "method": "PROPFIND",
          "url": "https://192.168.2.20:5006/",
          "httpVersion": "unknown",
          "headers": [
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
            },
            {
              "name": "Origin",
              "value": "null"
            },
            {
              "name": "authorization",
              "value": "Basic YW5kcmU6ZX"
            },
            {
              "name": "depth",
              "value": "1"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "unknown",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_INSECURE_RESPONSE"
        },
        "cache": {},
        "timings": {
          "blocked": -1,
          "dns": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "ssl": -1
        },
        "serverIPAddress": ""
      }
    ]
  }
}`

**Comment by perry-mitchell** [comment]
Thanks @andre-dierker - this is slightly better. We can see the `authorization` here is mentioned there correctly, so the request from buttercup looks correct.

What NAS are you using? Are you using a self-signed certificate at all (could be the issue)? Can you try on HTTP?

**Comment by andre-dierker** [comment]
this is a webdav only Nginx
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [],
    "entries": [
      {
        "startedDateTime": "2017-05-20T18:49:04.708Z",
        "time": 0,
        "request": {
          "method": "PROPFIND",
          "url": "https://207.xxx.xxx.xxx/dav/",
          "httpVersion": "unknown",
          "headers": [
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
            },
            {
              "name": "Origin",
              "value": "null"
            },
            {
              "name": "authorization",
              "value": "Basic dGVzdDp0ZXN0"
            },
            {
              "name": "depth",
              "value": "1"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "unknown",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_INSECURE_RESPONSE"
        },
        "cache": {},
        "timings": {
          "blocked": -1,
          "dns": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "ssl": -1
        },
        "serverIPAddress": ""
      }
    ]
  }
}

Both use self-signed certificates.

**Comment by perry-mitchell** [comment]
@andre-dierker I've edited your 2 last posts - just remember to hide sensitive information like the value in the auth header, and use github markdown formatting to make the JSON easier to read 😉

I think in most cases self-signed certs will fail.. Browsers (like Chrome, which is used in this project via Electron) will **by default** reject self-signed certs unless you explicitly allow it somehow.

**Comment by andre-dierker** [comment]
no worries, no productive passwords were posted (test) and sorry for unformatted json.
@perry-mitchell seems like, this is the problem. Http is working fine and a valid cert too. 
It's impossible to use a ss-Cert? What about a warning message?

**Comment by perry-mitchell** [comment]
Well there's S.O. answers like [this one](http://stackoverflow.com/a/38989441/966338) which seem to show [some way](https://electron.atom.io/docs/api/app/#event-certificate-error) of handling self-signed certificates.

To be honest, however, I don't particularly see the usefulness of having them supported. It would be substantial dev effort to build some kind of interface into the Electron app to support these, and this would also make using them in the Chrome extension very tricky. Free tools like [LetsEncrypt](https://letsencrypt.org/) allow for almost instant verified certificates for publicly exposed servers, and for internal use I would suggest just using HTTP (or, if your router works like mine and supports it, just allow it to route the external domain name internally so you can just hit the same server + SSL cert anywhere).

Right now I don't see any use case for self-signed certificates. Glad you found the issue!
