### ISSUE TITLE
Unhandled error when trying to load an archive from Dropbox

### ISSUE THREAD

**Issue by valentinebm** [buttercup/buttercup#264]
Screenshot:
<img width="911" alt="screen shot 2017-05-25 at 17 26 06" src="https://cloud.githubusercontent.com/assets/19521894/26444837/90c194e2-4170-11e7-97b8-a15793d86e91.png">

Trying Buttercup for the first time. Created my first archive, saved it on my computer. Since I wanted to connect my archive with the Buttercup extension, I uploaded it on Dropbox. I then tried to load the archive from Dropbox to the Buttercup Desktop app - to make sure that everything will be synched. This is when I get the error.

**Comment by perry-mitchell** [comment]
Thanks for reporting @valentinebm - What version of Buttercup are you using? If possible, could you also try to create a _new_ archive through Buttercup and its Dropbox integration to see if that works? It'd help us narrow it down.

**Comment by valentinebm** [comment]
Thanks @perry-mitchell - I'm using Version 0.16.0 (0.16.0). 

Tried:
- create a new archive through Buttercup, directly saving it to Dropbox as follows:
<img width="863" alt="screen shot 2017-05-26 at 11 24 34" src="https://cloud.githubusercontent.com/assets/19521894/26479470/07621226-4206-11e7-9924-206e280c4b1c.png">
- loading that same archive in Buttercup, but getting the same error:
<img width="864" alt="screen shot 2017-05-26 at 11 23 31" src="https://cloud.githubusercontent.com/assets/19521894/26479486/21bde514-4206-11e7-9e21-93d1a1ae084c.png">

Note: the archive was properly created and exists in my Dropbox.

Am I doing something wrong? 

Cheers

**Comment by perry-mitchell** [comment]
Hi @valentinebm - what I meant was create an archive in dropbox using the "Load from Cloud Services" option in the root menu. See if that loads..

**Comment by sallar** [comment]
@perry-mitchell @valentinebm I have seen this error and I'm currently investigating :)

**Comment by sallar** [comment]
@perry-mitchell @valentinebm Found the issue and fixed, it will go out in next release soon (tonight perhaps). Watch out for the update notice :)
