### ISSUE TITLE
Version shows the version that is available for update

### ISSUE THREAD

**Issue by matthaias** [buttercup/buttercup#267]
The current version shows 0.16.1, but it also says 0.16.1 is available to update in the right bottom corner. See Screenshots:

![bildschirmfoto 2017-05-28 um 08 28 28](https://cloud.githubusercontent.com/assets/1446082/26526551/a87378a6-437f-11e7-90f8-4d953bd71abe.png)
![bildschirmfoto 2017-05-28 um 08 29 04](https://cloud.githubusercontent.com/assets/1446082/26526553/bb28e2ba-437f-11e7-8a9e-5022f2da9918.png)

**Comment by perry-mitchell** [comment]
Hi @matthaias - I'm not able to replicate this issue. Looks to be some problem with the update server and the versions exchanged between that and the app. 

Could you try restarting the application? Does it change anything? I have a feeling this one might be very hard to track down if it's repeatable.

**Comment by matthaias** [comment]
Sorry for the bad information, i didn't expect that this is a bigger problem :). Yesterday i clicked on the button to install the newest version. Buttercup was closed then (should it not restart automatically?). After the restart the button was not visible anymore. But now, after the new release i have the same with the new version.

![bildschirmfoto 2017-05-29 um 08 52 14](https://cloud.githubusercontent.com/assets/1446082/26539325/1f4095b4-444c-11e7-95d4-4f0d080b24ca.png)

This problem is also if i close and start Buttercup again. 

But if a remember correct, the first start was correct with `installed version: 0.16.1` and `new version: 0.17.0`. 

Sorry, i think i don't have more information. Can you tell me what else i can do to give you more information?

**Comment by perry-mitchell** [comment]
It shouldn't automatically install the new version, that should happen once you click the update link (right @sallar?).

So you're saying that you're running v0.17.0 but still seeing the update message for 0.17.0? And if you click update, it remains at 0.17.0 and the update message comes back?

**Comment by matthaias** [comment]
> So you're saying that you're running v0.17.0 but still seeing the update message for 0.17.0? And if you click update, it remains at 0.17.0 and the update message comes back?

No, maybe i was not clear at this point. I didn't update, but Buttercup says i use `0.17.0` (so i should have `0.16.1`). Once i update, the message dissapears - at least yesterday after the update from `0.16.0` to `0.16.1`.

**Comment by sallar** [comment]
@matthaias @perry-mitchell I think I know what's the problem. if you get the update notice and "do not install" and close the app, the message will stay in state but wont do anything... I probably need to clear that message if you close the app without installing the update.

**Comment by matthaias** [comment]
@sallar can i do anything? Do you need more information?

**Comment by perry-mitchell** [comment]
> I probably need to clear that message if you close the app without installing the update

Why would you want to clear it? Wouldn't you want it shown still if the app is opened again?

This is quite a quirky one. We could roll our own update notification with something like [this](https://developer.github.com/v3/repos/releases/#get-the-latest-release). I couldn't get it to work in browser but the docs show it as available.

**Comment by sallar** [comment]
@perry-mitchell it needs to be compatible with Squirrel Mac/Windows

**Comment by sallar** [comment]
Also we need to clear it because if you quit the app, it will automatically install it anyway, and that's what causes this bug. The message is still there although the new version has been installed!
