### ISSUE TITLE
Impossible to create New Group

### ISSUE THREAD

**Issue by anarchogeek** [buttercup/buttercup#283]
Hello,

I just installed Buttercup for the first time. I wanted to create a new group, but when I click on the button "+ New  Group" i get an "Unhandled Error".

Here is a screenshot:
![image](https://user-images.githubusercontent.com/11022440/26954323-9e97f1ca-4caf-11e7-8e45-6ae6fdff488f.png)

**Comment by perry-mitchell** [comment]
I was able to reproduce on 0.17.1:
![image](https://user-images.githubusercontent.com/3869469/26960870-2e016e62-4ce3-11e7-85c2-b27362326b37.png)

Seems that the **New Group** button doesn't work at all with the latest release. @anarchogeek right-click seems to function. We'll get on this right away.

**Comment by anarchogeek** [comment]
When I right-click on "+ New Group", I get the next menu (New group, Title Ascending, Descending). But then when clicking (or right-clicking or entering) on "New Group", I get the exact same error.

**Comment by perry-mitchell** [comment]
@anarchogeek we're checking on it now, and should hopefully have a fix out shortly. Sorry for the inconvenience..

**Comment by anarchogeek** [comment]
No problem, thank you for your work and your fast answers ;-)

**Comment by sallar** [comment]
@anarchogeek This is fixed now and will be released in a few minutes. Thanks for the report :)
