### ISSUE TITLE
[Enhancement] Password generator

### ISSUE THREAD

**Issue by simonbcn** [buttercup/buttercup#287]
It would be nice a password generator in desktop app and Firefox extension.

**Comment by sallar** [comment]
@simonbcn The desktop app has a built in password generator right now. The browser extensions will get one as well soon.

**Comment by perry-mitchell** [comment]
@simonbcn I've created an [issue on the extension repo](https://github.com/buttercup/buttercup-browser-extension/issues/77) for this.
