### ISSUE TITLE
Chrome extension : 404 when owncloud is located in a subfolder

### ISSUE THREAD

**Issue by tomatlscomm** [buttercup/buttercup#294]
Hello.

I have an issue with the chrome extension, trying to connect via owncloud.
My ownclound URL is like : 
https://XXX.com/cloud/

But when the extension try to connect, it check this URL : 
https://XXX.com/remote.php/webdav/ 
404 (Not Found)

It should try : 
https://XXX.com/cloud/remote.php/webdav/ 
404 (Not Found)

Regards

**Comment by sallar** [comment]
Thanks @tomatlscomm, does this work correctly in our Desktop application though? Have you tried it?

**Comment by perry-mitchell** [comment]
Checking in the desktop app would be a good idea. Did you @tomatlscomm enter it as `https://XXX.com/cloud` in the URL field of the new ownCloud connection? It won't automatically add the `/cloud` portion obviously..

**Comment by tomatlscomm** [comment]
Hello

IN the desktop app it work fine. 
Yes I have set this full url https://xxx.com/cloud/

Regards

**Comment by perry-mitchell** [comment]
Ok, I can confirm that this is a bug. I've moved it to the extension where it belongs: https://github.com/buttercup/buttercup-browser-extension/issues/80
